USE sorc_db;

CREATE TABLE `production` (
	`id` INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`code` VARCHAR(50) NOT NULL,
	`name` VARCHAR(100) NOT NULL
)ENGINE=INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE `unit` (
	`id` INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NOT NULL,
	`symbol` VARCHAR(10) NOT NULL
)ENGINE=INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE `plan_change` (
	`id` INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`date` DATE NULL
)ENGINE=INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE `plan` (
	`id` INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`position` INTEGER NOT NULL,
	`product_id` INTEGER NOT NULL,
	`name` VARCHAR(100) NULL,
	`price` DOUBLE NULL,
	`amount` DOUBLE NOT NULL,
	`begin` DATE NULL,
	`end` DATE NULL,
	`unit_id` INTEGER NOT NULL,
	`comment` VARCHAR(150) NULL,
        `plan_change_id` INTEGER NOT NULL,
	FOREIGN KEY (`product_id`) REFERENCES `production` (`id`) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (`unit_id`) REFERENCES `unit` (`id`) ON UPDATE CASCADE ON DELETE CASCADE,
        FOREIGN KEY (`plan_change_id`) REFERENCES `plan_change` (`id`) ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE=INNODB DEFAULT CHARACTER SET utf8;